module1 resolved
js-tasks-ru/jsbasic-20230302_lizavetka-b pull request #2
Opened 2023-03-07 17:56 UTC by el-brouk

2023-03-07 17:56 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-03-08 11:31 UTC, SinimaWath requested changes

2023-03-08 11:31 UTC, SinimaWath commented on 1-module/2-task/index.js
> +  }
Нет смысла в if, если результат операции и так будет boolean: `Boolean(name) && !name.includes(' ') && name.length > 3`

2023-03-08 11:31 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  }
Тут тоже можно просто: `return str.includes('1xbet') || str.includes('xxx')`

2023-03-09 17:04 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-03-10 20:09 UTC, SinimaWath approved these changes

2023-03-10 20:10 UTC, merged